## Data science

- A field of science that studies, analize and performs various steps on the data to get valuable insights
- eg: google, maps, amazon, uber, netflix
- It has some powerful libraries or packages
    - numpy, pandas, matplotlib
    - numpy is used to scientific calculations
    - pandas are used for data manipulation, analysis and cleaning
    - matplotlib is used to visualize the data

### Numpy

- It means Numerical Python
- It is one of the packages/libraries in datascience
- Here we deal with array's
- The main purpose of this package is to do scientific calculations 
    - log, linear algebra, Fourier transform, Trigonometry and exponential
- smaller memory consumption and better run time

In [4]:
import numpy
a = np.array([3, 5, 7])
print(a)
type(a) # n dimentional array

[3 5 7]


numpy.ndarray

In [5]:
import numpy as np

In [6]:
b = np.array([[3, 4, 5], [7, 8, 9], [10, 11, 12]])
b

array([[ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
### preddefined functions
print(type(b))
print(b.dtype) # returns the data type present in the array
print(b.ndim)
print(a.ndim)  # returns number of rows in an array
print(b.shape) # returns shape of array
print(b.size)
np.__version__

<class 'numpy.ndarray'>
int32
2
1
(3, 3)
9


'1.18.5'

### range()

In [16]:
ar = np.array(range(5))
print(ar)

[0 1 2 3 4]


In [18]:
ar1 = np.array(range(1, 10))
print(ar1)

[1 2 3 4 5 6 7 8 9]


In [19]:
ar2 = np.array(range(1, 20, 3))
print(ar2)

[ 1  4  7 10 13 16 19]


### arange()

In [20]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [21]:
y = np.arange(1, 20, 2)
print(y)

[ 1  3  5  7  9 11 13 15 17 19]


### reshape()

In [23]:
a1 = np.arange(25).reshape(5, 5)
print(a1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [24]:
b

array([[ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
b.reshape(1, 9)
print(b)

[[ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


In [31]:
b1 = np.arange(12).reshape(-1, 4)
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
o = np.ones((2, 4), dtype = int)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
p = np.zeros((2, 4), dtype = int)
p

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
o = np.ones((2, 4), dtype = int)
o * 2

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [40]:
o = np.full((2, 4), 7)
o

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [42]:
e = np.eye(4, dtype = int)
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [44]:
n = np.arange(9).reshape(3, 3)
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
np.diag(n) # to print the diagnol elements of an array

array([0, 4, 8])

In [47]:
np.diag(n).sum() # return sum of diagnal elements

12