### Continuation of numpy

In [4]:
import numpy as np
a = np.linspace(1, 20, 4) # returns equally spaced numbers with in range
a

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

## random()

In [10]:
r = np.random.randint(10)
print(r)
r1 = np.random.randint(5, 10)
print(r1)
r2 = np.random.randint(1, 10, 3) # third argument represents number of values to be returned
print(r2)
r3 = np.random.randint(10, 100, (2, 4))
print(r3)
r4 = np.random.randint(10, 50, 12).reshape(3, 4)
print(r4)

2
6
[2 6 4]
[[66 37 75 24]
 [11 76 20 20]]
[[41 46 33 48]
 [12 22 30 23]
 [11 44 12 49]]


In [11]:
n = np.random.random(3)
n

array([0.06978464, 0.89735474, 0.74379916])

In [12]:
n1 = np.random.randn(4)
n1

array([-0.97340681,  0.70663934, -0.28757217, -0.45880962])

In [13]:
n2 = np.random.randint(-5, 5, 5)
n2

array([ 4, -4,  4,  3, -2])

In [14]:
## slicing

r = np.random.randint(10, 100, (4, 4))
r

array([[22, 98, 26, 27],
       [11, 75, 44, 45],
       [26, 82, 87, 81],
       [42, 31, 80, 47]])

In [15]:
r[0]

array([22, 98, 26, 27])

In [16]:
r[0: 2]

array([[22, 98, 26, 27],
       [11, 75, 44, 45]])

In [17]:
r[0:2, 0:2]

array([[22, 98],
       [11, 75]])

In [31]:
r[:, 1]

array([98, 75, 82, 31])

In [18]:
r

array([[22, 98, 26, 27],
       [11, 75, 44, 45],
       [26, 82, 87, 81],
       [42, 31, 80, 47]])

In [24]:
a = np.matrix('1, 2; 5, 7')
b = np.matrix('7, 8; 10, 15')
print(a)
print(b)

[[1 2]
 [5 7]]
[[ 7  8]
 [10 15]]


In [25]:
print(np.add(a, b))

[[ 8 10]
 [15 22]]


In [26]:
a + b

matrix([[ 8, 10],
        [15, 22]])

In [27]:
np.subtract(a, b)

matrix([[-6, -6],
        [-5, -8]])

In [28]:
np.matmul(a, b)

matrix([[ 27,  38],
        [105, 145]])

In [29]:
np.multiply(a, b)

matrix([[  7,  16],
        [ 50, 105]])

In [32]:
a

matrix([[1, 2],
        [5, 7]])

In [33]:
a > 7

matrix([[False, False],
        [False, False]])

In [34]:
a[a > 3]

matrix([[5, 7]])

In [35]:
a[a > 3].sum()

12

### Scientific computation

In [36]:
m = np.arange(16).reshape(8, 2)
m

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [38]:
print(np.mean(m))

7.5


In [39]:
np.median(m)

7.5

In [40]:
np.std(m)

4.6097722286464435

In [41]:
np.var(m)

21.25

In [42]:
np.dot(a, b)

matrix([[ 27,  38],
        [105, 145]])

In [43]:
np.log(0)

<ipython-input-43-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [44]:
np.log(1)

0.0

In [45]:
np.log([1, 2, 3, 4])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [46]:
np.exp(6)

403.4287934927351

In [47]:
np.log(np.exp(5))

5.0

In [48]:
print(dir(np), end = ' ')

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [49]:
np.sin(0)

0.0

In [50]:
np.cos(0)

1.0

In [51]:
np.tan(0)

0.0

# Pandas

- means paneldata
- it is one of the datascience package
- used for data manipulation,analysis and cleaning
- It contains two data structures
    - 1. Series
    - 2. DataFrames
- sequence of data
- A data frame is data with rows and columns

In [53]:
import pandas as pd

In [54]:
pd.__version__

'1.0.5'

In [55]:
st = 'Hello'
pd.Series(st)

0    Hello
dtype: object

In [57]:
s1 = "Good evening all".split()
pd.Series(s1)

0       Good
1    evening
2        all
dtype: object


In [60]:
l = [123, "Kotesh", 5.65974]
pd.Series(l, index = ['int', 'str', 'float'])

int          123
str       Kotesh
float    5.65974
dtype: object

In [61]:
t = ('a', 'e', 'i', 'o', 'u')
pd.Series(t, index = ['v1', 'v2', 'v3', 'v4', 'v5'])

v1    a
v2    e
v3    i
v4    o
v5    u
dtype: object

In [63]:
dic = {'k1' : 145, 'k2' : "Koti", 'k3' : 8.5}
pd.Series(dic)

k1     145
k2    Koti
k3     8.5
dtype: object

In [64]:
s = "Hello all welcome to python session".split()
pd.DataFrame(s)

0
0    Hello
1      all
2  welcome
3       to
4   python
5  session

In [66]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
pd.DataFrame(l)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [68]:
t = (1, 4, 5, 'Koti')
pd.DataFrame(t, index = [1, 2, 3, 4])

0
1     1
2     4
3     5
4  Koti

In [69]:
dic

{'k1': 145, 'k2': 'Koti', 'k3': 8.5}

In [70]:
pd.DataFrame(dic, index = (1, 2, 3))

k1    k2   k3
1  145  Koti  8.5
2  145  Koti  8.5
3  145  Koti  8.5